flaresolverr:
  flaresolverr_url: http://localhost:8191/v1
  retry: 5
  delay: 5
  max_timeout: 60
database:
  type: sqlite
  user: root
  password: ''
  host: localhost
  name: scraper
  port: 3306
  charset: utf8mb4
  db_file: db.sqlite3
logger:
  level: INFO
  file: scraper.log
  format: '%(asctime)s | %(levelname)s | %(name)s | %(message)s | %(filename)s:%(lineno)d'
ocr:
  pytesseract_path: C:\Program Files\Tesseract-OCR\tesseract.exe
  cache_path: ocr_cache.json
